import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

import Product from "../models/Product";
import ProductCard from "../components/ProductCard";
import Spinner from "../components/Spinner";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const allProducts = trpc.products.getAll.useQuery();  
  const postMutation = trpc.products.add.useMutation();
  const deleteMutation = trpc.products.removeAll.useMutation();
  
  const handleNewEntry = async () => {
    // Generates a product with default values
    const testProduct = new Product();

    postMutation.mutateAsync({
      id: testProduct.id,
      name: testProduct.name,
      description: testProduct.description,
      slug: testProduct.slug,
      price: testProduct.price,
      inventory: testProduct.inventory,
    }).then( () => router.reload())
  }

  const handleWipeAll = async () =>
    deleteMutation.mutateAsync()
      .then( () => router.reload());

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner />

      <main className="container mx-auto my-3 flex flex-col items-center justify-center p-4">

        <div className="flex flex-wrap w-full pt-6 pb-6">
          {
            allProducts.isFetching
            ? <Spinner />
            : allProducts.data && allProducts.data.length > 0
            ? <>
                <h2 className="text-3xl text-gray-700">
                  Our products
                </h2>
                <ul className="w-full px-10 grid sm:grid-cols-2 md:grid-cols-4 gap-4">
                {
                  allProducts.data.map(
                    (product, i) =>
                      <ProductCard product={product} key={i} />
                    )
                  }
                </ul>
              </>
            : <div className="flex flex-wrap w-full justify-center items-center font-bold my-12">
                <h3 className="w-full text-center text-3xl">
                  There&apos;s nothing here! 🕵️‍♂️
                </h3>
                <h4 className="block w-full text-center text-xl text-gray-500">
                  Try <Link href='/new' className="underline font-semibold">creating a new product</Link>
                </h4>
              </div>
          }
        </div>

      </main>
      <section className=" bg-gray-500 w-full pt-8">
        <header>
          <h2 className="text-center text-3xl text-white">
            Other actions
          </h2>
        </header>
        <div className="flex justify-evenly w-full py-12">
          <button onClick={handleNewEntry}
            className='bg-blue-500 text-white p-6 rounded-lg text-lg'
          >
            ✒ Register default product
          </button>
          <button onClick={handleWipeAll}
            className='bg-blue-500 text-white p-6 rounded-lg text-lg'
          >
            🔥 Wipe all products from DB
          </button>
        </div>
      </section>
    </>
  );
};

export default Home;

const randomImageURL = ():string => {
  const options = [
    'https://www.seekpng.com/png/full/258-2588310_coffee-bobs-bag-of-coffee-beans-png.png',
    'https://i.pinimg.com/originals/5c/9f/71/5c9f71b2e196ccf71e72eb88b9f75be8.png',
    'https://flowbite.s3.amazonaws.com/blocks/marketing-ui/hero/phone-mockup.png',
  ];
  const randomIndex = Math.floor(Math.random() * options.length);
  return options[randomIndex] as string;
}

const HeroBanner: React.FC = () => {
  /// Based on: https://flowbite.com/blocks/marketing/hero/

  return (
    <section className="bg-white dark:bg-gray-900">
      <div className="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
          <div className="mr-auto place-self-center lg:col-span-7">
              <h1 className="max-w-2xl mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl dark:text-white">
                Whatever you need, whenever you want it.
              </h1>
              <p className="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
                Anything, we will quite literally travel the entire globe in order to fulfill your wishes, as long as it is listed in our products 😉
              </p>
              <Link target="_blank" referrerPolicy="no-referrer" href='https://www.github.com/catneep' className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
                  Learn more
              </Link> 
          </div>
          <div className="hidden lg:mt-0 lg:col-span-5 lg:flex">
              {/* <img src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/hero/phone-mockup.png" alt="mockup" /> */}
              <img src={randomImageURL()} alt="hero image" />
          </div>                
      </div>
    </section>
  );
}
